# Generated by Django 4.0.5 on 2022-06-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
